### ISSUE TITLE
Speed Data

### ISSUE THREAD

**Issue by bleeckerj** [vermont42/GpxLocationManager#1]
Hello

I'm assuming that GpxLocationManager is not producing speed data, only location data? Just checking before I fork and add this. Any pointers as to where to fiddle?

**Comment by vermont42** [comment]
Sorry about the slow reply. I just saw it.

I'm not aware that CLLocationManager can report speed data, and I did not attempt to include this functionality in GpxLocationManager. Ordinarily, apps use time and distance traveled to compute speed, but I can imagine scenarios in which it would be useful to get speed from CLLocationManager. To add functionality you would modify GpxLocationManager.swift and, if your data comes from GPX files, GpxParser.swift.

**Comment by nkanetka** [comment]
@vermont42 I've got a working copy that simulates speed and course on my fork. I have not converted it to Swift 3.0 syntax but if I get time in the next little while, I can do that and make a PR. One thing to note is that this Pod may be very useful in the future given that location simulation with Automation Tools in Xcode 8 has been [removed](https://forums.developer.apple.com/thread/48936). With this in mind, I'd be willing to put some time into this project. Let me know what you think/what your plans are?

**Comment by vermont42** [comment]
Thanks for offering. I would likely accept a PR for Swift 3.0 or speed simulation.

I did the Swift 3.0 conversion for [RaceRunner](https://github.com/vermont42/RaceRunner), which has `GpxLocationManager` embedded in it, and the conversion was pretty painless.

**Comment by vermont42** [comment]
Looks like this is done.
