### ISSUE TITLE
Demo Crashes on Launch on Device

### ISSUE THREAD

**Issue by vermont42** [vermont42/GpxLocationManager#13]
@nkanetka When I run the `Demo` target on my iPhone (not in simulator), it crashes on launch with an error message similar to `dyld: Library not loaded: @rpath; Reason: image not found`. I added `GpxLocationManager.framework` as an embedded binary in the `Demo` target, which solved the problem. Before I PR this fix, do you agree that this is the correct solution?

**Comment by nkanetka** [comment]
Yep, that sounds right. Thanks for catching that!

**Comment by vermont42** [comment]
Done in the next PR.
