### ISSUE TITLE
does not recognize the "wpt" tag as used by Apple

### ISSUE THREAD

**Issue by ovdm** [vermont42/GpxLocationManager#17]
I fixed this, but I do not have permission to push the change

**Comment by ovdm** [comment]
Hi Josh,

We have an app called RealtorBuddy. It streamlines the realtors door-knocking activity for prospecting. 
It relies heavily on location services. For testing and demos we used the ability in Simulators to load GPX files. 
It was always a bit of problem, because the simulator ignored the timestamps for the way points and now the ability is completely gone. 

You library is very use-full. I found two bugs and fixed them and just wanted to push them back. I am not familiar with what type of process is being used. I can also just mail you the files. 

Oscar van der Meer
oscar@catlife.com

**Comment by vermont42** [comment]
Thanks for describing your use case. I am delighted that you find GpxLocationManager useful. 

Submitting a PR is the usual process for requesting that changes be incorporated into a repo. It can be intimidating, but I’m happy to take you through it via Skype. If you prefer not to PR, you can email me the modified file(s) at vermontcoder at gmail dot com.

**Comment by ovdm** [comment]
Prefer to learn how to do it the proper way. I tried to create a pull request, but got an authentication error. if you want to use Skype my id is oscar_van_der_meer
