### ISSUE TITLE
Need a tag

### ISSUE THREAD

**Issue by hsavit1** [vermont42/GpxLocationManager#3]
Hi, 

I'm trying to install this via Cocoapods but I think your podspec is broken...

I've noticed that you don't have a tag specified

**Comment by hsavit1** [comment]
it should say 1.0.0

<img width="458" alt="screen shot 2016-04-18 at 5 00 26 pm" src="https://cloud.githubusercontent.com/assets/5156236/14619766/1ea19c70-0587-11e6-999f-4037a2870f72.png">

**Comment by vermont42** [comment]
Thanks for spotting that! Please let me know if the fix does not work for you. You have a lovely dog.

**Comment by hsavit1** [comment]
it works great. thanks for this amazingly useful little library

**Comment by vermont42** [comment]
Thanks again. I am closing the issue.
