### ISSUE TITLE
DateFormatter in GpxParser

### ISSUE THREAD

**Issue by vinzenzweber** [vermont42/GpxLocationManager#4]
I had to change the dateFormat to "yyyy-MM-dd'T'HH:mm:ss'.000Z'" for a GPX file I downloaded from runtastic.com. Would be great if you could update that. I have to admit I am too lazy to create a pull request. Sorry.

**Comment by vermont42** [comment]
I would likely accept a pull request to fix this. The version of `GpxLocationManager` in [RaceRunner](https://github.com/vermont42/RaceRunner) works with Runtastic data.
